CONTIKI = ../contiki

PROJECT_SOURCEFILES +=  basicTree.c print_float.c Bayes_Laplace_Classify.c


CONTIKI_WITH_RIME = 1

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include
