

%% Calcular la potencia para diferentes ventanas e interferencias
calc_power_consumption_wind_5_int_0
calc_power_consumption_wind_10_int_0
calc_power_consumption_wind_15_int_0
calc_power_consumption_wind_20_int_0
calc_power_consumption_wind_25_int_0
calc_power_consumption_wind_30_int_0
calc_power_consumption_wind_35_int_0

calc_power_consumption_wind_5_int_70
calc_power_consumption_wind_10_int_70
calc_power_consumption_wind_15_int_70
calc_power_consumption_wind_20_int_70
calc_power_consumption_wind_25_int_70
calc_power_consumption_wind_30_int_70
calc_power_consumption_wind_35_int_70

%% rpl
calc_power_consumption_rpl_leaf


%% Calculo de la potencia variando el porcentaje de interferencia
 calc_power_consumption_vary_int

%% Consolidar la informacion 
consolidado_power_trace_int_0

consolidado_power_trace_int_70

%% Consolidado RPL y CITTT

Consolidado_RPL_CITTT