
%% definir las constantes para el nodo: Re-Mote
def_powertrace_constants


%% Calcular la potencia para diferentes ventanas e interferencias
calc_power_consumption_wind_5_int_0
calc_power_consumption_wind_10_int_0
calc_power_consumption_wind_15_int_0
calc_power_consumption_wind_20_int_0
calc_power_consumption_wind_25_int_0
calc_power_consumption_wind_30_int_0
calc_power_consumption_wind_35_int_0

calc_power_consumption_wind_5_int_70
calc_power_consumption_wind_10_int_70
calc_power_consumption_wind_15_int_70
calc_power_consumption_wind_20_int_70
calc_power_consumption_wind_25_int_70
calc_power_consumption_wind_30_int_70
calc_power_consumption_wind_35_int_70

%% Consolidar la informacion 
consolidado_power_trace_int_0

consolidado_power_trace_int_70