
% La diferencia entre det_int_0_wind_5_v2 y det_int_0_wind_5 es que:
% 1.   det_int_0_wind_5_v2: Se envia el paquete de manera deterministica: cada 1
%      segundo
% 2.   det_int_0_wind_5: Se envia el paquete de manera aleatoria, entre
%      [0,2] segundos


% % for a window = 5 int 0 
% clock_time_wind_5_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','B2:B60');
% all_cpu_wind_5_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','E2:E60');
% all_lpm_wind_5_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','F2:F60');
% all_transmit_wind_5_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','G2:G60');
% all_listen_wind_5_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','H2:H60');
% all_idle_transmit_wind_5_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','I2:I60');
% all_idle_listen_wind_5_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','J2:J60');
% cpu_wind_5_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','K2:K60');
% lpm_wind_5_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','L2:L60');
% transmit_wind_5_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','M2:M60');
% listen_wind_5_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','N2:N60');
% idle_transmit_wind_5_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','O2:O60');
% idle_listen_wind_5_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','P2:P60');
% 
% % for a window = 10 int 0 
% clock_time_wind_10_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','B2:B60');
% all_cpu_wind_10_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','E2:E60');
% all_lpm_wind_10_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','F2:F60');
% all_transmit_wind_10_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','G2:G60');
% all_listen_wind_10_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','H2:H60');
% all_idle_transmit_wind_10_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','I2:I60');
% all_idle_listen_wind_10_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','J2:J60');
% cpu_wind_10_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','K2:K60');
% lpm_wind_10_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','L2:L60');
% transmit_wind_10_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','M2:M60');
% listen_wind_10_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','N2:N60');
% idle_transmit_wind_10_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','O2:O60');
% idle_listen_wind_10_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','P2:P60');
% 
% % for a window = 15 int 0 
% clock_time_wind_15_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','B2:B65');
% all_cpu_wind_15_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','E2:E65');
% all_lpm_wind_15_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','F2:F65');
% all_transmit_wind_15_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','G2:G65');
% all_listen_wind_15_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','H2:H65');
% all_idle_transmit_wind_15_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','I2:I65');
% all_idle_listen_wind_15_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','J2:J65');
% cpu_wind_15_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','K2:K65');
% lpm_wind_15_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','L2:L65');
% transmit_wind_15_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','M2:M65');
% listen_wind_15_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','N2:N65');
% idle_transmit_wind_15_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','O2:O65');
% idle_listen_wind_15_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','P2:P65');
% 
% % for a window = 20 int 0 
% clock_time_wind_20_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','B2:B61');
% all_cpu_wind_20_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','E2:E61');
% all_lpm_wind_20_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','F2:F61');
% all_transmit_wind_20_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','G2:G61');
% all_listen_wind_20_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','H2:H61');
% all_idle_transmit_wind_20_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','I2:I61');
% all_idle_listen_wind_20_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','J2:J61');
% cpu_wind_20_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','K2:K61');
% lpm_wind_20_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','L2:L61');
% transmit_wind_20_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','M2:M61');
% listen_wind_20_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','N2:N61');
% idle_transmit_wind_20_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','O2:O61');
% idle_listen_wind_20_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','P2:P61');
% 
% % for a window = 25 int 0 
% clock_time_wind_25_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','B2:B63');
% all_cpu_wind_25_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','E2:E63');
% all_lpm_wind_25_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','F2:F63');
% all_transmit_wind_25_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','G2:G63');
% all_listen_wind_25_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','H2:H63');
% all_idle_transmit_wind_25_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','I2:I63');
% all_idle_listen_wind_25_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','J2:J63');
% cpu_wind_25_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','K2:K63');
% lpm_wind_25_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','L2:L63');
% transmit_wind_25_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','M2:M63');
% listen_wind_25_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','N2:N63');
% idle_transmit_wind_25_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','O2:O63');
% idle_listen_wind_25_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','P2:P63');
% 
% % for a window = 30 int 0 
% clock_time_wind_30_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','B2:B84');
% all_cpu_wind_30_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','E2:E84');
% all_lpm_wind_30_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','F2:F84');
% all_transmit_wind_30_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','G2:G84');
% all_listen_wind_30_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','H2:H84');
% all_idle_transmit_wind_30_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','I2:I84');
% all_idle_listen_wind_30_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','J2:J84');
% cpu_wind_30_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','K2:K84');
% lpm_wind_30_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','L2:L84');
% transmit_wind_30_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','M2:M84');
% listen_wind_30_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','N2:N84');
% idle_transmit_wind_30_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','O2:O84');
% idle_listen_wind_30_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','P2:P84');
% 
% % for a window = 35 int 0 
% clock_time_wind_35_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','B2:B155');
% all_cpu_wind_35_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','E2:E155');
% all_lpm_wind_35_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','F2:F155');
% all_transmit_wind_35_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','G2:G155');
% all_listen_wind_35_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','H2:H155');
% all_idle_transmit_wind_35_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','I2:I155');
% all_idle_listen_wind_35_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','J2:J155');
% cpu_wind_35_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','K2:K155');
% lpm_wind_35_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','L2:L155');
% transmit_wind_35_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','M2:M155');
% listen_wind_35_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','N2:N155');
% idle_transmit_wind_35_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','O2:O155');
% idle_listen_wind_35_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','P2:P155');


% for a window = 5 int 0  _v2
clock_time_wind_5_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','B2:B62');
all_cpu_wind_5_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','E2:E62');
all_lpm_wind_5_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','F2:F62');
all_transmit_wind_5_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','G2:G62');
all_listen_wind_5_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','H2:H62');
all_idle_transmit_wind_5_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','I2:I62');
all_idle_listen_wind_5_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','J2:J62');
cpu_wind_5_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','K2:K62');
lpm_wind_5_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','L2:L62');
transmit_wind_5_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','M2:M62');
listen_wind_5_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','N2:N62');
idle_transmit_wind_5_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','O2:O62');
idle_listen_wind_5_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0_v2.xlsx','powertrace_wind_5_int_0_v2','P2:P62');

% for a window = 10 int 0 _v2
clock_time_wind_10_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','B2:B63');
all_cpu_wind_10_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','E2:E63');
all_lpm_wind_10_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','F2:F63');
all_transmit_wind_10_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','G2:G63');
all_listen_wind_10_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','H2:H63');
all_idle_transmit_wind_10_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','I2:I63');
all_idle_listen_wind_10_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','J2:J63');
cpu_wind_10_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','K2:K63');
lpm_wind_10_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','L2:L63');
transmit_wind_10_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','M2:M63');
listen_wind_10_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','N2:N63');
idle_transmit_wind_10_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','O2:O63');
idle_listen_wind_10_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0_v2.xlsx','powertrace_wind_10_int_0_v2','P2:P63');

% for a window = 15 int 0 _v2
clock_time_wind_15_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','B2:B140');
all_cpu_wind_15_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','E2:E140');
all_lpm_wind_15_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','F2:F140');
all_transmit_wind_15_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','G2:G140');
all_listen_wind_15_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','H2:H140');
all_idle_transmit_wind_15_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','I2:I140');
all_idle_listen_wind_15_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','J2:J140');
cpu_wind_15_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','K2:K140');
lpm_wind_15_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','L2:L140');
transmit_wind_15_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','M2:M140');
listen_wind_15_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','N2:N140');
idle_transmit_wind_15_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','O2:O140');
idle_listen_wind_15_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0_v2.xlsx','powertrace_wind_15_int_0_v2','P2:P140');

% for a window = 20 int 0 _v2
clock_time_wind_20_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','B2:B183');
all_cpu_wind_20_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','E2:E183');
all_lpm_wind_20_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','F2:F183');
all_transmit_wind_20_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','G2:G183');
all_listen_wind_20_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','H2:H183');
all_idle_transmit_wind_20_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','I2:I183');
all_idle_listen_wind_20_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','J2:J183');
cpu_wind_20_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','K2:K183');
lpm_wind_20_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','L2:L183');
transmit_wind_20_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','M2:M183');
listen_wind_20_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','N2:N183');
idle_transmit_wind_20_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','O2:O183');
idle_listen_wind_20_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0_v2.xlsx','powertrace_wind_20_int_0_v2','P2:P183');

% for a window = 25 int 0 _v2
clock_time_wind_25_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','B2:B280');
all_cpu_wind_25_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','E2:E280');
all_lpm_wind_25_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','F2:F280');
all_transmit_wind_25_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','G2:G280');
all_listen_wind_25_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','H2:H280');
all_idle_transmit_wind_25_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','I2:I280');
all_idle_listen_wind_25_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','J2:J280');
cpu_wind_25_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','K2:K280');
lpm_wind_25_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','L2:L280');
transmit_wind_25_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','M2:M280');
listen_wind_25_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','N2:N280');
idle_transmit_wind_25_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','O2:O280');
idle_listen_wind_25_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0_v2.xlsx','powertrace_wind_25_int_0_v2','P2:P280');

% for a window = 30 int 0 _v2
clock_time_wind_30_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','B2:B184');
all_cpu_wind_30_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','E2:E184');
all_lpm_wind_30_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','F2:F184');
all_transmit_wind_30_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','G2:G184');
all_listen_wind_30_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','H2:H184');
all_idle_transmit_wind_30_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','I2:I184');
all_idle_listen_wind_30_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','J2:J184');
cpu_wind_30_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','K2:K184');
lpm_wind_30_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','L2:L184');
transmit_wind_30_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','M2:M184');
listen_wind_30_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','N2:N184');
idle_transmit_wind_30_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','O2:O184');
idle_listen_wind_30_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0_v2.xlsx','powertrace_wind_30_int_0_v2','P2:P184');

% for a window = 35 int 0 _v2
clock_time_wind_35_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','B2:B255');
all_cpu_wind_35_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','E2:E255');
all_lpm_wind_35_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','F2:F255');
all_transmit_wind_35_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','G2:G255');
all_listen_wind_35_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','H2:H255');
all_idle_transmit_wind_35_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','I2:I255');
all_idle_listen_wind_35_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','J2:J255');
cpu_wind_35_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','K2:K255');
lpm_wind_35_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','L2:L255');
transmit_wind_35_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','M2:M255');
listen_wind_35_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','N2:N255');
idle_transmit_wind_35_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','O2:O255');
idle_listen_wind_35_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0_v2.xlsx','powertrace_wind_35_int_0_v2','P2:P255');

% for a window = 5 int 70 
clock_time_wind_5_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','B2:B181');
all_cpu_wind_5_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','E2:E181');
all_lpm_wind_5_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','F2:F181');
all_transmit_wind_5_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','G2:G181');
all_listen_wind_5_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','H2:H181');
all_idle_transmit_wind_5_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','I2:I181');
all_idle_listen_wind_5_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','J2:J181');
cpu_wind_5_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','K2:K181');
lpm_wind_5_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','L2:L181');
transmit_wind_5_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','M2:M181');
listen_wind_5_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','N2:N181');
idle_transmit_wind_5_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','O2:O181');
idle_listen_wind_5_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_70.xlsx','powertrace_wind_5_int_70','P2:P181');

% for a window = 10 int 70 
clock_time_wind_10_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','B2:B428');
all_cpu_wind_10_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','E2:E428');
all_lpm_wind_10_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','F2:F428');
all_transmit_wind_10_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','G2:G428');
all_listen_wind_10_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','H2:H428');
all_idle_transmit_wind_10_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','I2:I428');
all_idle_listen_wind_10_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','J2:J428');
cpu_wind_10_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','K2:K428');
lpm_wind_10_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','L2:L428');
transmit_wind_10_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','M2:M428');
listen_wind_10_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','N2:N428');
idle_transmit_wind_10_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','O2:O428');
idle_listen_wind_10_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_70.xlsx','powertrace_wind_10_int_70','P2:P428');

% for a window = 15 int 70 
clock_time_wind_15_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','B2:B186');
all_cpu_wind_15_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','E2:E186');
all_lpm_wind_15_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','F2:F186');
all_transmit_wind_15_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','G2:G186');
all_listen_wind_15_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','H2:H186');
all_idle_transmit_wind_15_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','I2:I186');
all_idle_listen_wind_15_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','J2:J186');
cpu_wind_15_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','K2:K186');
lpm_wind_15_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','L2:L186');
transmit_wind_15_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','M2:M186');
listen_wind_15_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','N2:N186');
idle_transmit_wind_15_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','O2:O186');
idle_listen_wind_15_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_70.xlsx','powertrace_wind_15_int_70','P2:P186');

% for a window = 20 int 70 
clock_time_wind_20_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','B2:B192');
all_cpu_wind_20_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','E2:E192');
all_lpm_wind_20_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','F2:F192');
all_transmit_wind_20_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','G2:G192');
all_listen_wind_20_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','H2:H192');
all_idle_transmit_wind_20_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','I2:I192');
all_idle_listen_wind_20_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','J2:J192');
cpu_wind_20_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','K2:K192');
lpm_wind_20_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','L2:L192');
transmit_wind_20_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','M2:M192');
listen_wind_20_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','N2:N192');
idle_transmit_wind_20_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','O2:O192');
idle_listen_wind_20_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_70.xlsx','powertrace_wind_20_int_70','P2:P192');

% for a window = 25 int 70 
clock_time_wind_25_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','B2:B206');
all_cpu_wind_25_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','E2:E206');
all_lpm_wind_25_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','F2:F206');
all_transmit_wind_25_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','G2:G206');
all_listen_wind_25_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','H2:H206');
all_idle_transmit_wind_25_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','I2:I206');
all_idle_listen_wind_25_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','J2:J206');
cpu_wind_25_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','K2:K206');
lpm_wind_25_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','L2:L206');
transmit_wind_25_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','M2:M206');
listen_wind_25_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','N2:N206');
idle_transmit_wind_25_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','O2:O206');
idle_listen_wind_25_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_70_v2.xlsx','powertrace_wind_25_int_70_v2','P2:P206');

% for a window = 30 int 70 
clock_time_wind_30_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','B2:B1630');
all_cpu_wind_30_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','E2:E1630');
all_lpm_wind_30_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','F2:F1630');
all_transmit_wind_30_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','G2:G1630');
all_listen_wind_30_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','H2:H1630');
all_idle_transmit_wind_30_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','I2:I1630');
all_idle_listen_wind_30_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','J2:J1630');
cpu_wind_30_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','K2:K1630');
lpm_wind_30_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','L2:L1630');
transmit_wind_30_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','M2:M1630');
listen_wind_30_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','N2:N1630');
idle_transmit_wind_30_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','O2:O1630');
idle_listen_wind_30_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_70_v2.xlsx','powertrace_wind_30_int_70_v2','P2:P1630');

% for a window = 35 int 70 
clock_time_wind_35_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','B2:B563');
all_cpu_wind_35_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','E2:E563');
all_lpm_wind_35_int_70           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','F2:F563');
all_transmit_wind_35_int_70      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','G2:G563');
all_listen_wind_35_int_70        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','H2:H563');
all_idle_transmit_wind_35_int_70 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','I2:I563');
all_idle_listen_wind_35_int_70   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','J2:J563');
cpu_wind_35_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','K2:K563');
lpm_wind_35_int_70               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','L2:L563');
transmit_wind_35_int_70          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','M2:M563');
listen_wind_35_int_70            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','N2:N563');
idle_transmit_wind_35_int_70     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','O2:O563');
idle_listen_wind_35_int_70       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_70_v2.xlsx','powertrace_wind_35_int_70_v2','P2:P563');

