% for a window = 5 int 0 
clock_time_wind_5_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','B2:B60');
all_cpu_wind_5_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','E2:E60');
all_lpm_wind_5_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','F2:F60');
all_transmit_wind_5_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','G2:G60');
all_listen_wind_5_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','H2:H60');
all_idle_transmit_wind_5_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','I2:I60');
all_idle_listen_wind_5_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','J2:J60');
cpu_wind_5_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','K2:K60');
lpm_wind_5_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','L2:L60');
transmit_wind_5_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','M2:M60');
listen_wind_5_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','N2:N60');
idle_transmit_wind_5_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','O2:O60');
idle_listen_wind_5_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_5_int_0.xlsx','powertrace_wind_5_int_0','P2:P60');

% for a window = 10 int 0 
clock_time_wind_10_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','B2:B60');
all_cpu_wind_10_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','E2:E60');
all_lpm_wind_10_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','F2:F60');
all_transmit_wind_10_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','G2:G60');
all_listen_wind_10_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','H2:H60');
all_idle_transmit_wind_10_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','I2:I60');
all_idle_listen_wind_10_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','J2:J60');
cpu_wind_10_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','K2:K60');
lpm_wind_10_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','L2:L60');
transmit_wind_10_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','M2:M60');
listen_wind_10_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','N2:N60');
idle_transmit_wind_10_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','O2:O60');
idle_listen_wind_10_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_10_int_0.xlsx','powertrace_wind_10_int_0','P2:P60');

% for a window = 15 int 0 
clock_time_wind_15_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','B2:B65');
all_cpu_wind_15_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','E2:E65');
all_lpm_wind_15_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','F2:F65');
all_transmit_wind_15_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','G2:G65');
all_listen_wind_15_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','H2:H65');
all_idle_transmit_wind_15_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','I2:I65');
all_idle_listen_wind_15_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','J2:J65');
cpu_wind_15_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','K2:K65');
lpm_wind_15_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','L2:L65');
transmit_wind_15_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','M2:M65');
listen_wind_15_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','N2:N65');
idle_transmit_wind_15_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','O2:O65');
idle_listen_wind_15_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_15_int_0.xlsx','powertrace_wind_15_int_0','P2:P65');

% for a window = 20 int 0 
clock_time_wind_20_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','B2:B61');
all_cpu_wind_20_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','E2:E61');
all_lpm_wind_20_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','F2:F61');
all_transmit_wind_20_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','G2:G61');
all_listen_wind_20_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','H2:H61');
all_idle_transmit_wind_20_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','I2:I61');
all_idle_listen_wind_20_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','J2:J61');
cpu_wind_20_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','K2:K61');
lpm_wind_20_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','L2:L61');
transmit_wind_20_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','M2:M61');
listen_wind_20_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','N2:N61');
idle_transmit_wind_20_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','O2:O61');
idle_listen_wind_20_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_20_int_0.xlsx','powertrace_wind_20_int_0','P2:P61');

% for a window = 25 int 0 
clock_time_wind_25_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','B2:B63');
all_cpu_wind_25_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','E2:E63');
all_lpm_wind_25_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','F2:F63');
all_transmit_wind_25_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','G2:G63');
all_listen_wind_25_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','H2:H63');
all_idle_transmit_wind_25_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','I2:I63');
all_idle_listen_wind_25_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','J2:J63');
cpu_wind_25_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','K2:K63');
lpm_wind_25_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','L2:L63');
transmit_wind_25_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','M2:M63');
listen_wind_25_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','N2:N63');
idle_transmit_wind_25_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','O2:O63');
idle_listen_wind_25_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_25_int_0.xlsx','powertrace_wind_25_int_0','P2:P63');

% for a window = 30 int 0 
clock_time_wind_30_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','B2:B84');
all_cpu_wind_30_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','E2:E84');
all_lpm_wind_30_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','F2:F84');
all_transmit_wind_30_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','G2:G84');
all_listen_wind_30_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','H2:H84');
all_idle_transmit_wind_30_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','I2:I84');
all_idle_listen_wind_30_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','J2:J84');
cpu_wind_30_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','K2:K84');
lpm_wind_30_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','L2:L84');
transmit_wind_30_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','M2:M84');
listen_wind_30_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','N2:N84');
idle_transmit_wind_30_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','O2:O84');
idle_listen_wind_30_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_30_int_0.xlsx','powertrace_wind_30_int_0','P2:P84');

% for a window = 35 int 0 
clock_time_wind_35_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','B2:B155');
all_cpu_wind_35_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','E2:E155');
all_lpm_wind_35_int_0           = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','F2:F155');
all_transmit_wind_35_int_0      = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','G2:G155');
all_listen_wind_35_int_0        = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','H2:H155');
all_idle_transmit_wind_35_int_0 = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','I2:I155');
all_idle_listen_wind_35_int_0   = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','J2:J155');
cpu_wind_35_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','K2:K155');
lpm_wind_35_int_0               = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','L2:L155');
transmit_wind_35_int_0          = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','M2:M155');
listen_wind_35_int_0            = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','N2:N155');
idle_transmit_wind_35_int_0     = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','O2:O155');
idle_listen_wind_35_int_0       = xlsread('/home/seringsergio/Desktop/DGHS/BayesClassification/results_powertrace_wind/powertrace_wind_35_int_0.xlsx','powertrace_wind_35_int_0','P2:P155');

