CONTIKI = ../contiki

PROJECT_SOURCEFILES +=  Bayes_Laplace_Classify.c

CONTIKI_PROJECT = Bayes_Laplace_Classify.c
all: $(CONTIKI_PROJECT)

CONTIKI_WITH_RIME = 1

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include
